#pragma config(Sensor, S1,     Gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S2,     LineTracker1,   sensorEV3_Color)
#pragma config(Sensor, S3,     LineTracker2,   sensorNone)
#pragma config(Motor,  motorA,          Left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,          Right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          DropMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task drop()
{
	delay(500);
	setMotorSpeed(motorC,25);
}
task rightTurnAfterLine()
{
	resetGyro(Gyro);
	if(getColorReflected(LineTracker1) == 256 && getColorReflected(LineTracker2) == 256)
	{
		while(getGyroDegrees(Gyro)<90)
		{
			setMotorSpeed(Left,50);
			setMotorSpeed(Right,-50);
		}
	}

}
task leftTurnAfterLine()
{
	if(getColorReflected(LineTracker1)== 256 & getColorReflected(LineTracker2) == 256)
	{
		while(getGyroDegrees(S1)<-90)
		{
			setMotorSpeed(Left,-50);
			setMotorSpeed(Right,50);
		}
	}
task leftTurn()
{
	while(getGyroDegrees(Gyro)<-90)
		{
			setMotorSpeed(Left,-50);
			setMotorSpeed(Right,50);
		}
}
task rightTurn()
{
while(getGyroDegrees(Gyro)<90)
		{
			setMotorSpeed(Left,50);
			setMotorSpeed(Right,-50);
		}
}

task forward()
{
lineTrackLeft(LineTracker1,50,50,100);
}
task BottomLeft()
{
	delay(1000);
	forward();
}
task BottomMiddle()
{

}
task BottomRight()
{

}
task middleLeft()
{
	delay(2000);
	forward();
}
task middleMiddle()
{

}
task middleRight()
{

}
task topLeft()
{

}
